### ISSUE TITLE
Uninstalling the extension from podman desktop doesn't remove the registry entry

### ISSUE THREAD

**Issue by cbr7** [redhat-developer/podman-desktop-redhat-account-ext#84] opened 2024-03-12 14:08 UTC
If the extension is disabled/removed in Podman Desktop should the entry for Red Hat container registry be removed or should it still show as being available for use in Podman Desktop?

**Comment by odockal** [comment] 2024-03-12 15:33
@cbr7 I believe that in case when I close the podman desktop and I am logged out of the registry, it should behave the same when uninstalling (maybe even disabling the extension).

**Comment by benoitf** [comment] 2024-03-12 15:41
uninstall the extension will unregister the registry as this is the extension that is registering them

so uninstall = unregister all resources

**Comment by cbr7** [comment] 2024-03-12 16:16
@odockal @benoitf so if I understand you correctly that means that the behavior in the video is a bug, right?


https://github.com/redhat-developer/podman-desktop-redhat-account-ext/assets/106525396/0280578a-aff3-4dbb-a632-7076b2360d95

Since the registry remains after the extension is removed.

**Comment by odockal** [comment] 2024-03-12 16:20
@cbr7 I tend to agree this is a bug.

**Comment by benoitf** [comment] 2024-03-12 16:23
yes

**Comment by dgolovin** [comment] 2024-03-13 06:11
The subscription is not deactivated for podman VM too.

**Comment by dgolovin** [comment] 2024-03-13 19:07
> uninstall the extension will unregister the registry as this is the extension that is registering them

so uninstall = unregister all resources

@benoitf there is no way to distinguish what has triggered deactivate() call:
* uninstall
* disable
* exit from the application

If extension starts cleaning up everything in `deactivate()` it will also conflict with #39, because when it is fixed one is going to stay signed in between podman desktop sessions.

**Comment by benoitf** [comment] 2024-03-13 19:39
@dgolovin: I think I spoke too fast

extension is correctly unregistering the suggested registry so the icon is gone but yes user is still logged-in

**Comment by benoitf** [comment] 2024-03-13 19:40
so yes probably close as 'expected behaviour'

**Closed** 2024-04-09 11:39 UTC
Labels: bug, question
